dist: trusty
sudo: false
cache: bundler
language: ruby
arch: 
  - amd64
  - ppc64le

before_install: 
  - if [[ "$TRAVIS_CPU_ARCH" = "ppc64le" ]]; then bundle update --bundler; fi
  - gem update --remote bundler

install:
  - bundle install --retry=3

script:
  - bundle exec rubocop
  - bundle exec rake
